name: "Workflow to Convert Jupyter Noteboks"
on:
  schedule:
    - cron: "59 23 * * 6"

jobs:
  build:
    name: Converts the Notebooks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ../action/
